name: Build and Release

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 8
      uses: actions/setup-java@v4
      with:
        java-version: '8'
        distribution: 'temurin'
        
    - name: Build JAR
      run: |
        chmod +x build_linux.sh
        ./build_linux.sh
        
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: GraalSuite
        path: bin/GraalSuite.jar
